# fly.toml app configuration file generated for pocket-base-docker on 2024-01-11T13:14:46+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pocket-base-docker"
primary_region = "sin"

[build]
  image = "imanilchaudhari/pocketbase:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
